# Generated by Django 3.2 on 2022-04-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='ingredians',
            new_name='ingrediants',
        ),
    ]
